#配置端口号
server:
  port: 8081
  #上下文
  servlet.context-path: /hello
  tomcat.uri-encoding: UTF-8
logging:
  #日志级别（com.example包下的所有class的日志级别设置为Debug）
  level.com.example: DEBUG
  #日志输出位置
  file: /home/sang/workspace/log.log
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages.encoding: UTF-8
  datasource:
    name: mysql
    url: jdbc:mysql://10.4.126.72:3306/cq
    username: NEU
    password: Neusoft@123
    #连接池类型druid
    type: com.alibaba.druid.pool.DruidDataSource
    #type: org.apache.tomcat.jdbc.pool.DataSource tomcat内置连接池
    driver-class-name: com.mysql.jdbc.Driver
    #tomcat内置连接池没有用到
    tomcat:
      #最大连接数
      max-active: 150
      #最大闲置连接数
      min-idle: 20
      #最大等待时间
      max-wait: 5000
      #指定update是否自动提交
      default-auto-commit: true
#  redis:
#    database: 5
#    host: 10.4.126.72
#    port: 7001
#    timeout: 3000s
    # 连接池中的最大空闲连接，默认值也是8。
mybatis:
  #扫描mapper.xml
  mapper-locations: classpath:sqlmapper/*.xml
  #关联model
  type-aliases-package: com.example.model
  #使用配置文件的方式配置
  #config-location: mybatis-config.xml