package com.example.model.data;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table cq_user
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class UserDO implements Serializable {
    /**
     * Database Column Remarks:
     *   账号，系统内部唯一标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cq_user.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cq_user.nick_name
     *
     * @mbg.generated
     */
    private String nickName;

    /**
     * Database Column Remarks:
     *   手机号：user_type为2时有值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cq_user.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     * Database Column Remarks:
     *   真实姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cq_user.true_name
     *
     * @mbg.generated
     */
    private String trueName;

    /**
     * Database Column Remarks:
     *   证件号码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cq_user.identity_code
     *
     * @mbg.generated
     */
    private String identityCode;

    /**
     * Database Column Remarks:
     *   证件类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cq_user.identity_kind
     *
     * @mbg.generated
     */
    private Short identityKind;

    /**
     * Database Column Remarks:
     *   用户类型 1邮箱注册用户 2手机登录用户
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cq_user.user_type
     *
     * @mbg.generated
     */
    private Short userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cq_user.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cq_user.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cq_user.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cq_user.create_by
     *
     * @mbg.generated
     */
    private Integer createBy;

    /**
     * Database Column Remarks:
     *   是否删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cq_user.is_del
     *
     * @mbg.generated
     */
    private Short isDel;

    /**
     * Database Column Remarks:
     *   是否激活
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cq_user.is_active
     *
     * @mbg.generated
     */
    private Short isActive;

    /**
     * Database Column Remarks:
     *   是否接受促销邮件推送 1是0否
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cq_user.accept_promotion
     *
     * @mbg.generated
     */
    private Short acceptPromotion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cq_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cq_user.user_id
     *
     * @return the value of cq_user.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cq_user.user_id
     *
     * @param userId the value for cq_user.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cq_user.nick_name
     *
     * @return the value of cq_user.nick_name
     *
     * @mbg.generated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cq_user.nick_name
     *
     * @param nickName the value for cq_user.nick_name
     *
     * @mbg.generated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cq_user.phone
     *
     * @return the value of cq_user.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cq_user.phone
     *
     * @param phone the value for cq_user.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cq_user.true_name
     *
     * @return the value of cq_user.true_name
     *
     * @mbg.generated
     */
    public String getTrueName() {
        return trueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cq_user.true_name
     *
     * @param trueName the value for cq_user.true_name
     *
     * @mbg.generated
     */
    public void setTrueName(String trueName) {
        this.trueName = trueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cq_user.identity_code
     *
     * @return the value of cq_user.identity_code
     *
     * @mbg.generated
     */
    public String getIdentityCode() {
        return identityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cq_user.identity_code
     *
     * @param identityCode the value for cq_user.identity_code
     *
     * @mbg.generated
     */
    public void setIdentityCode(String identityCode) {
        this.identityCode = identityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cq_user.identity_kind
     *
     * @return the value of cq_user.identity_kind
     *
     * @mbg.generated
     */
    public Short getIdentityKind() {
        return identityKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cq_user.identity_kind
     *
     * @param identityKind the value for cq_user.identity_kind
     *
     * @mbg.generated
     */
    public void setIdentityKind(Short identityKind) {
        this.identityKind = identityKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cq_user.user_type
     *
     * @return the value of cq_user.user_type
     *
     * @mbg.generated
     */
    public Short getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cq_user.user_type
     *
     * @param userType the value for cq_user.user_type
     *
     * @mbg.generated
     */
    public void setUserType(Short userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cq_user.email
     *
     * @return the value of cq_user.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cq_user.email
     *
     * @param email the value for cq_user.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cq_user.create_time
     *
     * @return the value of cq_user.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cq_user.create_time
     *
     * @param createTime the value for cq_user.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cq_user.modify_time
     *
     * @return the value of cq_user.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cq_user.modify_time
     *
     * @param modifyTime the value for cq_user.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cq_user.create_by
     *
     * @return the value of cq_user.create_by
     *
     * @mbg.generated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cq_user.create_by
     *
     * @param createBy the value for cq_user.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cq_user.is_del
     *
     * @return the value of cq_user.is_del
     *
     * @mbg.generated
     */
    public Short getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cq_user.is_del
     *
     * @param isDel the value for cq_user.is_del
     *
     * @mbg.generated
     */
    public void setIsDel(Short isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cq_user.is_active
     *
     * @return the value of cq_user.is_active
     *
     * @mbg.generated
     */
    public Short getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cq_user.is_active
     *
     * @param isActive the value for cq_user.is_active
     *
     * @mbg.generated
     */
    public void setIsActive(Short isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cq_user.accept_promotion
     *
     * @return the value of cq_user.accept_promotion
     *
     * @mbg.generated
     */
    public Short getAcceptPromotion() {
        return acceptPromotion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cq_user.accept_promotion
     *
     * @param acceptPromotion the value for cq_user.accept_promotion
     *
     * @mbg.generated
     */
    public void setAcceptPromotion(Short acceptPromotion) {
        this.acceptPromotion = acceptPromotion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cq_user
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", nickName=").append(nickName);
        sb.append(", phone=").append(phone);
        sb.append(", trueName=").append(trueName);
        sb.append(", identityCode=").append(identityCode);
        sb.append(", identityKind=").append(identityKind);
        sb.append(", userType=").append(userType);
        sb.append(", email=").append(email);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", createBy=").append(createBy);
        sb.append(", isDel=").append(isDel);
        sb.append(", isActive=").append(isActive);
        sb.append(", acceptPromotion=").append(acceptPromotion);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}